name: moduler_structure
description: Modulo para crear infraestructura
version: 0.0.1
maintainer: Veerne (@VeerneToor)
homepage: https://github.com/fluttercommunity/moduler_structure

dependencies:
  yaml: ^3.1.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.17.11
